name: simple_graphql_query_builder
description: A simple GraphQl query builder to generate query as String, used together with the package `graphql`
version: 0.0.2
homepage:
repository: https://github.com/ngthailam/SimpleGraphQlQueryBuilder

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: