name: simple_graphql_query_builder
description: A simple GraphQl query builder to generate query as String, used together with the package `graphql`
version: 0.1.0
homepage:
repository: https://github.com/ngthailam/SimpleGraphQlQueryBuilder/tree/main/simple_graphql_query_builder

environment:
  sdk: ">=2.17.5 <3.0.0"

platforms:
  android:
  ios:
  web:

dependencies:
  meta: ^1.7.0

dev_dependencies:
