name: simple_graphql_query_builder_gen
description: A generator for package simple_graphql_query_builder to reduce boilerplate code.
version: 0.2.0
homepage:
repository: https://github.com/ngthailam/SimpleGraphQlQueryBuilder/tree/main/simple_graphql_query_builder_gen

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  build:  ^2.3.0
  source_gen:  ^1.2.0
  analyzer: ^5.7.0
  simple_graphql_query_builder: ^0.2.2
  collection: ^1.17.0

dev_dependencies:
  build_runner:
  test: ^1.0.0

platforms:
  android:
  ios:
  web:
