name: simple_graphql_query_builder_gen
description: A generator for package simple_graphql_query_builder to reduce boilerplate code.
version: 0.0.1
homepage:
repository: https://github.com/ngthailam/SimpleGraphQlQueryBuilder/tree/main/simple_graphql_query_builder_gen

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  build:
  source_gen:
  simple_graphql_query_builder: ^0.0.3

dev_dependencies:
  # 4
  build_runner:
  # 5
  test: ^1.0.0

platforms:
  android:
  ios:
  web:
