name: simple_graphql_query_builder_gen
description: A generator for package simple_graphql_query_builder to reduce boilerplate code.
version: 0.1.1
homepage:
repository: https://github.com/ngthailam/SimpleGraphQlQueryBuilder/tree/main/simple_graphql_query_builder_gen

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  build:  ^2.3.1
  source_gen:  ^1.2.6
  analyzer: ^5.7.0
  simple_graphql_query_builder: ^0.1.0
  collection: ^1.17.1

dev_dependencies:
  # 4
  build_runner:
  # 5
  test: ^1.0.0

platforms:
  android:
  ios:
  web:
